// <auto-generated />
using LeBrowsPremiere.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeBrowsPremiere.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230210184236_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeBrowsPremiere.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("LeBrowsPremiere.Entities.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceId"));

                    b.Property<string>("ProvinceName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceId");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            ProvinceId = 1,
                            ProvinceName = "Alberta"
                        },
                        new
                        {
                            ProvinceId = 2,
                            ProvinceName = "British Columbia"
                        },
                        new
                        {
                            ProvinceId = 3,
                            ProvinceName = "Manitoba"
                        },
                        new
                        {
                            ProvinceId = 4,
                            ProvinceName = "New Brunswick"
                        },
                        new
                        {
                            ProvinceId = 5,
                            ProvinceName = "Newfoundland and Labrador"
                        },
                        new
                        {
                            ProvinceId = 6,
                            ProvinceName = "Northwest Territories"
                        },
                        new
                        {
                            ProvinceId = 7,
                            ProvinceName = "Nova Scotia"
                        },
                        new
                        {
                            ProvinceId = 8,
                            ProvinceName = "Nunavut"
                        },
                        new
                        {
                            ProvinceId = 9,
                            ProvinceName = "Ontario"
                        },
                        new
                        {
                            ProvinceId = 10,
                            ProvinceName = "Prince Edward Island"
                        },
                        new
                        {
                            ProvinceId = 11,
                            ProvinceName = "Quebec"
                        },
                        new
                        {
                            ProvinceId = 12,
                            ProvinceName = "Saskatchewan"
                        },
                        new
                        {
                            ProvinceId = 13,
                            ProvinceName = "Yukon"
                        });
                });

            modelBuilder.Entity("LeBrowsPremiere.Entities.Customer", b =>
                {
                    b.HasOne("LeBrowsPremiere.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });
#pragma warning restore 612, 618
        }
    }
}
